services:
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6378:6379"
    networks:
      - app_network


  app:
    container_name: f_backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - ./project/.env
    depends_on:
      - redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  staticfiles:
  mediafiles:
