services:
  redis:
    container_name: alibi_redis
    image: redis:latest
    networks:
      - app_network

  app:
    container_name: f_backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - ./project/.env
    depends_on:
      - redis
    networks:
      - app_network
    environment:
      - CELERY_BROKER_URL=redis://alibi_redis:6379/0
      - CELERY_RESULT_BACKEND=redis://alibi_redis:6379/0

  celery_worker:
    container_name: alibi_celery_worker
    build:
      context: .
    volumes:
      - .:/app:cached
    command: celery -A project worker --loglevel=info
    env_file:
      - ./project/.env
    depends_on:
      - redis
    networks:
      - app_network

  celery_beat:
    container_name: alibi_celery_beat
    build:
      context: .
    volumes:
      - .:/app:cached
    command: celery -A project beat --loglevel=info
    env_file:
      - ./project/.env
    depends_on:
      - redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  staticfiles:
  mediafiles:
