# Generated by Django 5.2.1 on 2025-06-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0003_usersubscription_checkout_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
