# Generated by Django 5.2.1 on 2025-06-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0005_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='stripe_session_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
