# Generated by Django 5.2.1 on 2025-07-02 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0006_paymenthistory_stripe_session_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='product_id',
            new_name='order_id',
        ),
    ]
