from django.urls import path

from gallery.rest.views.admin import (
    GalleryListCreateView,
    GalleryRetrieveUpdateDestroyView,
    AdminPhotoEditRequestView,
    AdminVideoAudioEditRequestView,
    AdminSouvenirRequestView,
    AdminPhotoEditRequestRetrieveView,
    AdminPhotoEditRequestUpdateStatusView,
    AdminVideoAudioEditRequestRetrieveView,
    AdminVideoAudioEditRequestUpdateStatusView,
    EditRequestDownloadView,
)

urlpatterns = [
    path(
        "",
        GalleryListCreateView.as_view(),
        name="gallery-list-create"
    ),
    path(
        "/photo-edit-requests",
        AdminPhotoEditRequestView.as_view(),
        name="admin-photo-edit-request"
    ),
    path(
        "/photo-edit-requests/<str:uid>",
        AdminPhotoEditRequestRetrieveView.as_view(),
        name="admin-photo-edit-request-retrieve"
    ),
    path(
        "/photo-edit-requests/<str:uid>/update-status",
        AdminPhotoEditRequestUpdateStatusView.as_view(),
        name="admin-photo-edit-request-update-status"
    ),
    path(
        "/video-audio-edit-requests",
        AdminVideoAudioEditRequestView.as_view(),
        name="admin-video-audio-edit-request"
    ),
    path(
        "/video-audio-edit-requests/<str:uid>",
        AdminVideoAudioEditRequestRetrieveView.as_view(),
        name="admin-video-audio-edit-request-retrieve"
    ),
    path(
        "/download",
        EditRequestDownloadView.as_view(),
        name="edit-request-download"
    ),
    path(
        "/video-audio-edit-requests/<str:uid>/update-status",
        AdminVideoAudioEditRequestUpdateStatusView.as_view(),
        name="admin-video-audio-edit-request-update-status"
    ),
    path(
        "/souvenir-requests",
        AdminSouvenirRequestView.as_view(),
        name="admin-souvenir-request"
    ),
    path(
        "/<str:uid>",
        GalleryRetrieveUpdateDestroyView.as_view(),
        name="gallery-retrieve-update-destroy"
    ),
]
