# Generated by Django 5.2.1 on 2025-09-10 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('title', models.CharField(blank=True, help_text='Please provide a title for the request', max_length=255, null=True)),
                ('description', models.TextField(help_text='Please describe the overall request')),
                ('special_note', models.TextField(blank=True, help_text='Please add any special notes', null=True)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('desire_delivery_date', models.DateTimeField(help_text='When would you like the changes delivered?')),
                ('shipping_address', models.TextField(blank=True, help_text='Please provide the shipping address', null=True)),
                ('additional_notes', models.TextField(blank=True, help_text='Please provide any additional notes', null=True)),
                ('request_type', models.CharField(blank=True, choices=[('photo_request', 'Photo Request'), ('video_request', 'Video Request'), ('audio_request', 'Audio Request'), ('souvenir_request', 'Souvenir Request'), ('other', 'Other')], default='other', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_edit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edit Request',
                'verbose_name_plural': 'Edit Requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('pdf', 'PDF'), ('docx', 'DOCX'), ('pptx', 'PPTX'), ('xlsx', 'XLSX'), ('other', 'Other')], default='other', max_length=10)),
                ('file', models.FileField(upload_to='gallery/')),
                ('is_public', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_galleries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_galleries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EditRequestGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('pdf', 'PDF'), ('docx', 'DOCX'), ('pptx', 'PPTX'), ('xlsx', 'XLSX'), ('other', 'Other')], default='other', max_length=10)),
                ('user_request_file', models.FileField(blank=True, help_text='Please upload the file you would like to edit', null=True, upload_to='user-requests/')),
                ('individual_note', models.TextField(blank=True, help_text='Specific instructions for this file (optional)', null=True)),
                ('file_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_response_file', models.FileField(blank=True, null=True, upload_to='responses/')),
                ('quantity', models.IntegerField(blank=True, default=1, help_text='Quantity of files to be edited or ordered', null=True)),
                ('edit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_files', to='gallery.editrequest')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_edit_responses', to=settings.AUTH_USER_MODEL)),
                ('gallery', models.ForeignKey(blank=True, help_text='Please select the gallery you would like to edit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_in', to='gallery.gallery')),
            ],
            options={
                'verbose_name': 'Edit Request Gallery',
                'verbose_name_plural': 'Edit Request Galleries',
                'ordering': ('-edit_request__created_at',),
            },
        ),
        migrations.AddField(
            model_name='editrequest',
            name='media_files',
            field=models.ManyToManyField(blank=True, related_name='edit_requests', through='gallery.EditRequestGallery', to='gallery.gallery'),
        ),
    ]
