# Generated by Django 5.2.1 on 2025-06-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editrequest',
            options={'ordering': ('-created_at',), 'verbose_name': 'Edit Request', 'verbose_name_plural': 'Edit Requests'},
        ),
        migrations.AlterModelOptions(
            name='editrequestgallery',
            options={'ordering': ('-edit_request__created_at',), 'verbose_name': 'Edit Request Gallery', 'verbose_name_plural': 'Edit Request Galleries'},
        ),
        migrations.AlterUniqueTogether(
            name='editrequestgallery',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='file',
            field=models.FileField(upload_to='gallery/'),
        ),
    ]
