# Generated by Django 5.2.1 on 2025-06-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_created_by_alter_gallery_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='title',
            field=models.CharField(blank=True, help_text='Please provide a title for the request', max_length=255, null=True),
        ),
    ]
