# Generated by Django 5.2.1 on 2025-06-16 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_editrequest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Please provide any additional notes', null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='Please provide the shipping address', null=True),
        ),
        migrations.AddField(
            model_name='editrequestgallery',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('pdf', 'PDF'), ('docx', 'DOCX'), ('pptx', 'PPTX'), ('xlsx', 'XLSX'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='editrequestgallery',
            name='user_request_file',
            field=models.FileField(blank=True, help_text='Please upload the file you would like to edit', null=True, upload_to='user-requests/'),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='media_files',
            field=models.ManyToManyField(blank=True, related_name='edit_requests', through='gallery.EditRequestGallery', to='gallery.gallery'),
        ),
        migrations.AlterField(
            model_name='editrequestgallery',
            name='gallery',
            field=models.ForeignKey(blank=True, help_text='Please select the gallery you would like to edit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_in', to='gallery.gallery'),
        ),
    ]
