# Generated by Django 5.2.1 on 2025-06-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_editrequest_additional_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='request_type',
            field=models.CharField(blank=True, choices=[('photo_request', 'Photo Request'), ('video_request', 'Video Request'), ('audio_request', 'Audio Request'), ('souvenir_request', 'Souvenir Request'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
    ]
