# Generated by Django 5.2.1 on 2025-06-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_editrequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
