# Generated by Django 5.2.1 on 2025-06-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_gallery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequestgallery',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, help_text='Quantity of files to be edited or ordered', null=True),
        ),
    ]
