# Generated by Django 5.2.1 on 2025-06-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_editrequestgallery_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editrequest',
            name='code',
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='code',
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True),
        ),
    ]
