# Generated by Django 5.2.1 on 2025-06-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at',), 'verbose_name': 'System User', 'verbose_name_plural': 'System Users'},
        ),
    ]
