# Generated by Django 5.2.1 on 2025-06-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
        ),
    ]
